USE [master]
GO
/****** Object:  Database [ProjetoBanco]    Script Date: 03/01/2023 22:39:18 ******/
CREATE DATABASE [ProjetoBanco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjetoBanco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ProjetoBanco.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjetoBanco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ProjetoBanco_log.ldf' , SIZE = 1088KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ProjetoBanco] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjetoBanco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProjetoBanco] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProjetoBanco] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProjetoBanco] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProjetoBanco] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProjetoBanco] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProjetoBanco] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ProjetoBanco] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProjetoBanco] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProjetoBanco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProjetoBanco] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProjetoBanco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProjetoBanco] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProjetoBanco] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProjetoBanco] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProjetoBanco] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProjetoBanco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProjetoBanco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProjetoBanco] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProjetoBanco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProjetoBanco] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProjetoBanco] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ProjetoBanco] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProjetoBanco] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ProjetoBanco] SET  MULTI_USER 
GO
ALTER DATABASE [ProjetoBanco] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProjetoBanco] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProjetoBanco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProjetoBanco] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ProjetoBanco] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ProjetoBanco]
GO
/****** Object:  Table [dbo].[Conta]    Script Date: 03/01/2023 22:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Conta](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CPF] [nvarchar](14) NOT NULL,
	[Nome] [nvarchar](60) NOT NULL,
	[Saldo] [float] NOT NULL,
 CONSTRAINT [PK_Conta] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [ProjetoBanco] SET  READ_WRITE 
GO


--OBS: Script gerado pelo SSMS - SQL Server Express v.12.0.2000.
